name: Docker Image CI

on:
  [workflow_dispatch]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: docker build . -t nathanwarrick/one-office-national-scraper:latest
      - name: push image to docker hub
        run: |
          docker login -u nathanwarrick -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push nathanwarrick/one-office-national-scraper:latest

